### ISSUE TITLE
how to use third party Map APIs?

### ISSUE THREAD

**Issue by GaoboLi** [Prograda/Skybolt#21]
"url": "http://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token={ssk.eyJ1IjoibGkxNDE0N...

I have filled in the access permit，but  “[0x00001398] [error]   Could not load image from XyzTileSource with URL template 'http://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token={sk.eyJ1IjoibGkxND”. I don`t know why, also I try bing map the same way, faild too，can sameone give me an example

**Comment by matthew-reid** [comment]
It looks like your token might be incorrectly formatted. I wouldn't expect it to start with a `{`.

You can either put the key directly in the url as you have done, or use {key} as the template in the url:
`http://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token={key}`

and put the key in your Skybolt config file (on windows, usually C:\Users\<userName>\AppData\Local\Skybolt\Settings.json), e.g if the key is 1234:
```
"tileApiKeys": {
       "mapbox": "1234"
    }
```
