### ISSUE TITLE
PlanetTileImagesLoader will go to pieces when “attributeLayer->getHighestAvailableLevel(key) ”not available;

### ISSUE THREAD

**Issue by GaoboLi** [Prograda/Skybolt#23]
@src\Skybolt\SkyboltVis\Renderable\Planet\Tile\PlanetTileImagesLoader.cpp 
line 200

you can put 

```
if (!images->attributeMapImage->image)
{
	images->attributeMapImage = std::nullopt;
}
```
in 
```
if (attributeKey)
{

}
```

**Comment by matthew-reid** [comment]
Fixed in https://github.com/Prograda/Skybolt/commit/026c9035622e0f0c0fd41a741e5d9b5ca39c41ee
