### ISSUE TITLE
How to turn off sunlight in the scene graph？

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#26]
When I was debugging, it was very inconvenient for me to have half of the world in the dark. Can you help me solve it?Thank you.

**Comment by matthew-reid** [comment]
You can set the ambient light level to artificially brighten the scene with `vis::Scene::setAmbientLightColor`. For example:

`engineRoot->setAmbientLightColor(osg::Vec3f(1, 1, 1));`

If you're running the SprocketApp, this can be done from the GUI:
![AmbientLight](https://github.com/Prograda/Skybolt/assets/2742081/b3be7843-a5c3-499c-9ed7-a01762d32de9)

**Comment by jiaxianghao** [comment]
Thank you.
