### ISSUE TITLE
Hao to add two maps in the scene graph?

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#27]
Hello matthew, my development environment cannot be connected to the internet, so I need to read map data from the geoserver. However, there is a blurry global map and a clear local map on the geoserver. After reading your source code, I found that it is impossible to add two maps. Do you have any good ideas?

**Comment by jiaxianghao** [comment]
Thank you.

**Comment by matthew-reid** [comment]
It's not directly supported, but you might be able to do what you want with any one of these 3 methods:
Method 1. Combine both maps into a single map hierarchy. For example, imagine a situation where the tiles follow a `<z>/<x>/<y>.png` naming convention, the low-res map goes up to level 8, and the high res map goes up to level 14. In that case you would combine the low res folders 0-8 into the same directory as the high-res folders 9-14.
Method 2. Use relative filesystem path to the tiles (this method doesn't work with http URL). You would specify the path to the tiles in the PlanetEarth.json as `"url": "MyTiles/z/x/y.png"`. You would then create two asset packages, one with the high res tiles, and one with the low res tiles, and both packages would have their tile hierarchy under a MyTiles folder. When the engine searches at runtime for a tile, it will search in both asset packages, and find the appropriate tile in the appropriate package.
Method 3. Create a custom TileSource, derived from the `TileSource` base class. This custom TileSource would wraps multiple tile sources. You'd have to write a custom `createImage` function which calls `createImage` on the appopriate wrapped TileSource for the tile level queried.

**Comment by jiaxianghao** [comment]
OK,I got it.
