### ISSUE TITLE
The SKYBOLT_CACHE_DIR environmental variable doesn't take effect.

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#28]
I am using the v1.3.3 of skybolt.Looking forward to your reply,thank you.

**Comment by jiaxianghao** [comment]
Thanks for your reply.

**Comment by jiaxianghao** [comment]
When I browse the source code, the mCacheDirectory member attribute in the CachedTileSource class is not set correctly.After make some modifications,the cache ability work correctly.

**Comment by matthew-reid** [comment]
Support for SKYBOLT_CACHE_DIR is not available in v1.3.3, it was was added in v1.5.

**Comment by jiaxianghao** [comment]
OK,I understand. Thank you.

**Comment by jiaxianghao** [comment]
I just download the source from github,and I find the latest version tag is v1.4.0.Hasn't the version 1.5 you mentioned been released yet? Or is there something wrong with my approach?

**Comment by jiaxianghao** [comment]
Ok,thanks for your explanation.
