### ISSUE TITLE
Can skyblt load tms tiles?

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#29]
When I use the XyzYileSource load the tms tile,I find the following Phenomenon.
![123](https://github.com/Prograda/Skybolt/assets/38557307/37e7f30d-b0e3-4bd5-a56a-46e0c9bb4a47)

I don't know if I'm doing the right thing

**Comment by jiaxianghao** [comment]
Look carefully at the top left corner of the earth

**Comment by matthew-reid** [comment]
Check that the `projection` for the TileSource is set correctly. The two options are "sphericalMercator" and "globalGeodetic". See `PlanetEarth.json` for an example.

**Comment by jiaxianghao** [comment]
The phenomenon of these two options is the same.Is there any other reasons?
