### ISSUE TITLE
How to remove all external forces on the helicopter uh60

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#31]
I am using the v1.4.0 of skybolt and I set the mess of the uh60 to zero.Then,I found the following phenomenon.

**Comment by jiaxianghao** [comment]
![Uploading 38C2C75C-4CAF-4437-A42E-902FBF622A21.jpeg…]()
![Uploading 21520339-427C-4060-A9C8-52DA4DEAB490.jpeg…]()
The first picture is the state of the program just starting, and the other picture is the state five minutes after startup.

**Comment by jiaxianghao** [comment]
Picture too big ,I will upload the picture tonight.

**Comment by jiaxianghao** [comment]
![D87623DF-0DA6-407A-A95D-7D4204399983](https://github.com/Prograda/Skybolt/assets/38557307/0308157e-cd67-4482-ab50-b6ea47454212)
![A4F60800-C69B-4D29-9F95-5622619B4028](https://github.com/Prograda/Skybolt/assets/38557307/bd52f88d-0332-4c72-a205-dd57a436b0e3)

**Comment by matthew-reid** [comment]
Zero mass isn't supported. If you want to disable all dynamics, you can call `entity->setDynamicsEnabled(false)`. You can also call `setDynamicsEnabled` on individual Entity components, like the helicopter's `DynamicBodyComponent`.
