### ISSUE TITLE
building the v1.5.0 with JSBSIM failed

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#33]
![屏幕截图 2023-06-06 213708](https://github.com/Prograda/Skybolt/assets/38557307/cc24ad69-8fc4-4fb3-ba4a-dcedea64500a)
Hi Matthew, The JSBSiM is download from the github(JSBSim-1.1.13-setup.exe).Do I have to compile JsbSim myself?

**Comment by matthew-reid** [comment]
It looks like Skybolt may not be linking to The JSBSim libraries. JSBSim is not yet supported by the Skybolt conan build, so you would need to to manually enable the BUILD_JSBSIM_PLUGIN in CMake and check that CMake successfully found the JSBSim libraries.

**Comment by jiaxianghao** [comment]
Do you compile your own JSBSiM library or download the exe from the Internet?

**Comment by jiaxianghao** [comment]
Actually,I built skybolt with cmake.
