### ISSUE TITLE
can not open include file: “SkyboltVis/Renderable/Planet/Tile/HeightMap.h”: No such file or directory

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#34]
Hi Matthew, When compiling skybolt, I added support for MAP_FEATURES_CONVERTER, which produced this error (I used V1.5.0). It should also exist in V1.4.0, but not in V1.3.3

**Comment by matthew-reid** [comment]
I just fixed the missing include it in the v1.5 branch. I've also I changed the `READOSM` CMake package name to `readosm` to make it consistant with the conan package. See commit 32be2df1e0db259ba5374da966ec223524304c64

**Comment by jiaxianghao** [comment]
Which version of ToolWindowManager are you using？

**Comment by matthew-reid** [comment]
The dependency version is defined in the skybolt conan build script (Conan/Recipes/toolwindowmanager/conanfile.py).

The version is:
        url: https://github.com/Piraxus/toolwindowmanager
        revision: b0bf1c107a3f7ed3ca7821cbd3f53db13bd1cc0a

**Comment by jiaxianghao** [comment]
@matthew-reid

**Comment by jiaxianghao** [comment]
@matthew-reid  I need your help.

**Comment by matthew-reid** [comment]
The assert is invalid, you can safely remove it. I've fixed it in fcafc6d264a047cb7fa240f3a1d6b0973f6f4e31

**Comment by jiaxianghao** [comment]
ok,thank you.
