### ISSUE TITLE
Customize the component display model

### ISSUE THREAD

**Issue by jiaxianghao** [Prograda/Skybolt#36]
Hi Matthew,I customized a component to add a cow to the helicopter (probably weird, but just for testing), but I found that the cow became transparent and was obscured by the terrain

**Comment by jiaxianghao** [comment]
`
static void loadVisualCow(Entity* entity, const EntityFactory::Context& context, const VisObjectsComponentPtr& visObjectsComponent, const SimVisBindingsComponentPtr& simVisBindingComponent, const nlohmann::json& json)
{
	vis::ModelConfig config;
	osg::ref_ptr<osg::MatrixTransform> transform = new osg::MatrixTransform;
	transform->addChild(osgDB::readNodeFile("cow.osg"));
	config.node = transform;

	vis::ModelPtr model = std::make_shared<vis::Model>(config);

	visObjectsComponent->addObject(model);

	auto rotor = entity->getFirstComponentRequired<ModelCowComponent>();
	auto node = entity->getFirstComponentRequired<Node>();

	SimVisBindingPtr simVis(new ModelVisComponent(rotor.get(), node.get(), model));
	simVisBindingComponent->bindings.push_back(simVis);
}`
The class ModelCowComponent is empty, and the class ModelVisComponent only set the cow's position and ratation.

**Comment by jiaxianghao** [comment]
@matthew-reid thank you.

**Comment by jiaxianghao** [comment]
If use the following method to load model, the loaded model is completly black
`	
vis::ModelPtr model = createVisualModel(json, *context.modelFactory);
visObjectsComponent->addObject(model);
`

**Comment by matthew-reid** [comment]
Does the cow have a texture? `vis::Model` uses the `PrincipledBrdf.frag` shader which expects an albedo (diffuse) texture. The texture should be assigned within the `.osg`. As a test, try replacing the cow with an existing model that is compatible with Skybolt e.g `Movers/Models/UH60/UH60_Fuselage.ive`.

**Comment by jiaxianghao** [comment]
When loading Movers/Models/UH60/UH60_Fuselage.ive,The problem described above did not occur.

**Comment by jiaxianghao** [comment]
Thank you.
