### ISSUE TITLE
conan version problem

### ISSUE THREAD

**Issue by LanFear-Li** [Prograda/Skybolt#39]
There are parameters --install-folder and --build-folder for conan install, after installed the latest conan there are no these parameters, could you please tell me the recommanded conan version for installation? Thanks.

**Comment by matthew-reid** [comment]
The --install-folder and --build-folder parameters were deprecated in conan 2.x. Currently Skybolt only supports conan 1.x. I'm using conan 1.64.0 which still supports these parameters.

I plan to upgrade to 2.x in the next few months. Until then, please try the commands again with 1.64.x.

**Comment by matthew-reid** [comment]
Conan 2 is now supported as of Skybolt 1.7.
