### ISSUE TITLE
Could not install packages with conan for v1.6

### ISSUE THREAD

**Issue by lminkov** [Prograda/Skybolt#41]
When I tried to use conan to install dependances I got the following errors:

Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.

C:\Projects\skybolt>conan install .\Skybolt-1.6.0 --install-folder=.\Skybolt-1.6.0-bld
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=17
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
cxxtimer/1.0.0@user/stable exports_sources: Copied 1 '.py' file: conanfile.py
cxxtimer/1.0.0@user/stable: The stored package has not changed
cxxtimer/1.0.0@user/stable: Exported revision: 6800f6f23f91506b3cc6f9b09dff2bae
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
px_sched/1.0.0@user/stable exports_sources: Copied 1 '.py' file: conanfile.py
px_sched/1.0.0@user/stable: The stored package has not changed
px_sched/1.0.0@user/stable: Exported revision: 2e397ad1498e9173257a81c1d0586472
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
Exporting package recipe
openscenegraph-mr/3.7.0@user/stable exports: File 'conandata.yml' found. Exporting it...
openscenegraph-mr/3.7.0@user/stable exports: Copied 1 '.yml' file: conandata.yml
openscenegraph-mr/3.7.0@user/stable exports_sources: Copied 1 '.txt' file: CMakeLists.txt
openscenegraph-mr/3.7.0@user/stable: The stored package has not changed
openscenegraph-mr/3.7.0@user/stable: Exported revision: 7f573637254084f1982fb4965edc52d4
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
mufft/1.0.0@user/stable exports_sources: Copied 1 '.py' file: conanfile.py
mufft/1.0.0@user/stable: The stored package has not changed
mufft/1.0.0@user/stable: Exported revision: 169df40695f3d585a69c498a51507567
WARN: *** Conan 1 is legacy and on a deprecation path ***
WARN: *** Please upgrade to Conan 2 ***
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'url'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'description'. It is recommended to add it as attribute
Exporting package recipe
xsimd/7.4.10@user/stable exports_sources: Copied 1 '.py' file: conanfile.py
xsimd/7.4.10@user/stable: The stored package has not changed
xsimd/7.4.10@user/stable: Exported revision: 62ea31468c19a6e9c1062687a9b86dfb
WARN: boost/1.75.0: requirement zlib/[>=1.2.11 <2] overridden by skybolt/1.6.0 to zlib/1.2.13
WARN: openscenegraph-mr/3.7.0@user/stable: requirement zlib/1.2.13 overridden by skybolt/1.6.0 to zlib/1.2.13
WARN: libcurl/8.0.1: requirement zlib/[>=1.2.11 <2] overridden by openscenegraph-mr/3.7.0@user/stable to zlib/1.2.13
WARN: openssl/3.2.2: requirement zlib/[>=1.2.11 <2] overridden by libcurl/8.0.1 to zlib/1.2.13
WARN: freetype/2.13.0: requirement libpng/[>=1.6 <2] overridden by openscenegraph-mr/3.7.0@user/stable to libpng/1.6.40
WARN: freetype/2.13.0: requirement zlib/[>=1.2.10 <2] overridden by openscenegraph-mr/3.7.0@user/stable to zlib/1.2.13
WARN: libpng/1.6.40: requirement zlib/[>=1.2.11 <2] overridden by freetype/2.13.0 to zlib/1.2.13
WARN: libtiff/4.5.1: requirement zlib/[>=1.2.11 <2] overridden by openscenegraph-mr/3.7.0@user/stable to zlib/1.2.13
WARN: readosm/1.1.0a: requirement expat/[>=2.6.2 <3] overridden by skybolt/1.6.0 to expat/2.5.0
WARN: readosm/1.1.0a: requirement zlib/[>=1.2.11 <2] overridden by skybolt/1.6.0 to zlib/1.2.13
Version ranges solved
    Version range '>=1.1 <4' required by 'libcurl/8.0.1' resolved to 'openssl/3.2.2' in local cache

conanfile.py (skybolt/1.6.0): Installing package
Requirements
    boost/1.75.0 from 'conancenter' - Cache
    brotli/1.1.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    catch2/2.13.8 from 'conancenter' - Cache
    cpp-httplib/0.10.1 from 'conancenter' - Cache
    cxxtimer/1.0.0@user/stable from local cache - Cache
    earcut/2.2.3 from 'conancenter' - Cache
    expat/2.5.0 from 'conancenter' - Cache
    freetype/2.13.0 from 'conancenter' - Cache
    getopt-for-visual-studio/20200201 from 'conancenter' - Cache
    giflib/5.2.1 from 'conancenter' - Cache
    glm/0.9.9.8 from 'conancenter' - Cache
    jbig/20160605 from 'conancenter' - Cache
    libcurl/8.0.1 from 'conancenter' - Cache
    libdeflate/1.19 from 'conancenter' - Cache
    libjpeg/9e from 'conancenter' - Cache
    libpng/1.6.40 from 'conancenter' - Cache
    libtiff/4.5.1 from 'conancenter' - Cache
    libwebp/1.3.2 from 'conancenter' - Cache
    mufft/1.0.0@user/stable from local cache - Cache
    nlohmann_json/3.10.5 from 'conancenter' - Cache
    opengl/system from 'conancenter' - Cache
    openscenegraph-mr/3.7.0@user/stable from local cache - Cache
    openssl/3.2.2 from 'conancenter' - Cache
    px_sched/1.0.0@user/stable from local cache - Cache
    readosm/1.1.0a from 'conancenter' - Cache
    xsimd/7.4.10@user/stable from local cache - Cache
    xz_utils/5.4.5 from 'conancenter' - Cache
    zlib/1.2.13 from 'conancenter' - Cache
    zstd/1.5.5 from 'conancenter' - Cache
Packages
    boost/1.75.0:9122dbc53b72d49447592b7c1471ee184105ccbd - Missing
    brotli/1.1.0:339a42a93ab71cc1532756ab68b57e03a9527302 - Missing
    bzip2/1.0.8:53b5fd22ba061620078deefdae9a437c5f693201 - Missing
    catch2/2.13.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    cpp-httplib/0.10.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    cxxtimer/1.0.0@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Missing
    earcut/2.2.3:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    expat/2.5.0:8e589e066a19f700666be77ed94ff8e8bc88ee10 - Missing
    freetype/2.13.0:ab90453798d425d2569b30b281e7ffd71b83ed38 - Missing
    getopt-for-visual-studio/20200201:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    giflib/5.2.1:998b27f2f059c06e17a06dde624b816c152a6d5d - Missing
    glm/0.9.9.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    jbig/20160605:3227e41c9aec6b7fc084139c2cd1f2b0510d9050 - Missing
    libcurl/8.0.1:a875f41e4829a262d98e23ace329473a9a7e8894 - Missing
    libdeflate/1.19:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Missing
    libjpeg/9e:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Missing
    libpng/1.6.40:8cfa2f2d9045fcd29f9c7fb36ce25c8202159f15 - Missing
    libtiff/4.5.1:b06705354880d696e63cf1069585aeaf0a4a7931 - Missing
    libwebp/1.3.2:060bb9d4f9d0ac5a39d27747e7f861ae5fc2baeb - Missing
    mufft/1.0.0@user/stable:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Missing
    nlohmann_json/3.10.5:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    openscenegraph-mr/3.7.0@user/stable:f7eca7b64e49f57c1d6bede269f3e575ce3e2e23 - Missing
    openssl/3.2.2:c47212d5fc818fd54769ccb1344e758f51a9aacb - Missing
    px_sched/1.0.0@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Missing
    readosm/1.1.0a:7ee818e3495b708a9b7b0dfddd7f5b3e06750468 - Missing
    xsimd/7.4.10@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Missing
    xz_utils/5.4.5:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Missing
    zlib/1.2.13:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b - Missing
    zstd/1.5.5:ec77614a77a3764b27d00f6ad0655478893ddf7e - Missing

Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.75.0:9122dbc53b72d49447592b7c1471ee184105ccbd
ERROR: Missing binary: brotli/1.1.0:339a42a93ab71cc1532756ab68b57e03a9527302
ERROR: Missing binary: bzip2/1.0.8:53b5fd22ba061620078deefdae9a437c5f693201
ERROR: Missing binary: cxxtimer/1.0.0@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: Missing binary: expat/2.5.0:8e589e066a19f700666be77ed94ff8e8bc88ee10
ERROR: Missing binary: freetype/2.13.0:ab90453798d425d2569b30b281e7ffd71b83ed38
ERROR: Missing binary: giflib/5.2.1:998b27f2f059c06e17a06dde624b816c152a6d5d
ERROR: Missing binary: jbig/20160605:3227e41c9aec6b7fc084139c2cd1f2b0510d9050
ERROR: Missing binary: libcurl/8.0.1:a875f41e4829a262d98e23ace329473a9a7e8894
ERROR: Missing binary: libdeflate/1.19:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: Missing binary: libjpeg/9e:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: Missing binary: libpng/1.6.40:8cfa2f2d9045fcd29f9c7fb36ce25c8202159f15
ERROR: Missing binary: libtiff/4.5.1:b06705354880d696e63cf1069585aeaf0a4a7931
ERROR: Missing binary: libwebp/1.3.2:060bb9d4f9d0ac5a39d27747e7f861ae5fc2baeb
ERROR: Missing binary: mufft/1.0.0@user/stable:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: Missing binary: openscenegraph-mr/3.7.0@user/stable:f7eca7b64e49f57c1d6bede269f3e575ce3e2e23
ERROR: Missing binary: openssl/3.2.2:c47212d5fc818fd54769ccb1344e758f51a9aacb
ERROR: Missing binary: px_sched/1.0.0@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: Missing binary: readosm/1.1.0a:7ee818e3495b708a9b7b0dfddd7f5b3e06750468
ERROR: Missing binary: xsimd/7.4.10@user/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: Missing binary: xz_utils/5.4.5:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: Missing binary: zlib/1.2.13:5a61a86bb3e07ce4262c80e1510f9c05e9b6d48b
ERROR: Missing binary: zstd/1.5.5:ec77614a77a3764b27d00f6ad0655478893ddf7e

brotli/1.1.0: WARN: Can't find a 'brotli/1.1.0' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=17, os=Windows
- Options: enable_debug=False, enable_log=False, enable_portable=False, enable_rbit=True, endianness=None, shared=False, target_bits=None
- Dependencies:
- Requirements:
- Package ID: 339a42a93ab71cc1532756ab68b57e03a9527302

ERROR: Missing prebuilt package for 'boost/1.75.0', 'brotli/1.1.0', 'bzip2/1.0.8', 'cxxtimer/1.0.0@user/stable', 'expat/2.5.0', 'freetype/2.13.0', 'giflib/5.2.1', 'jbig/20160605', 'libcurl/8.0.1', 'libdeflate/1.19', 'libjpeg/9e', 'libpng/1.6.40', 'libtiff/4.5.1', 'libwebp/1.3.2', 'mufft/1.0.0@user/stable', 'openscenegraph-mr/3.7.0@user/stable', 'openssl/3.2.2', 'px_sched/1.0.0@user/stable', 'readosm/1.1.0a', 'xsimd/7.4.10@user/stable', 'xz_utils/5.4.5', 'zlib/1.2.13', 'zstd/1.5.5'
Use 'conan search brotli/1.1.0@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=missing'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by matthew-reid** [comment]
Hi @lminkov, the error indicates that there are no pre-built binaries for your configuration (MSVC version etc) in the conan-center remote. You can tell conan to build them locally by adding `--build=missing` to the command:

```C:\Projects\skybolt>conan install .\Skybolt-1.6.0 --install-folder=.\Skybolt-1.6.0-bld --build=missing```
